#!/usr/bin/env node
const { Command } = require("commander");
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { marked } = require("marked");
const OpenAI = require("openai");

const program = new Command();
const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

program.name("vibe").description("Codebase thinking CLI").version("0.1.0");

function getFiles(dir, fileList = []) {
    const files = fs.readdirSync(dir);
    files.forEach((file) => {
        const filePath = path.join(dir, file);
        if (fs.statSync(filePath).isDirectory()) {
            if (!["node_modules", ".git"].includes(file)) {
                getFiles(filePath, fileList);
            }
        } else {
            fileList.push(filePath);
        }
    });
    return fileList;
}

function generateHTML(markdownOutput) {
    const renderedContent = marked(markdownOutput);
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Vibe Audit</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f3; color: #1a1a1a; padding: 2rem; }
  .container { max-width: 800px; margin: 0 auto; }
  .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem; }
  .header h1 { font-size: 22px; font-weight: 500; }
  .meta { font-size: 12px; color: #888; margin-top: 4px; }
  .badge { background: #1D9E75; color: white; font-size: 13px; padding: 6px 14px; border-radius: 8px; font-weight: 500; }
  .card { background: white; border: 0.5px solid #e0e0dc; border-radius: 12px; padding: 1.5rem; margin-bottom: 12px; }
  .card-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #aaa; margin-bottom: 12px; }
  .content h3 { font-size: 15px; font-weight: 500; margin: 1.4rem 0 0.6rem; color: #1a1a1a; }
  .content h3:first-child { margin-top: 0; }
  .content p { font-size: 14px; line-height: 1.8; color: #444; margin-bottom: 0.6rem; }
  .content ul { padding-left: 1.2rem; margin-bottom: 0.6rem; }
  .content li { font-size: 14px; line-height: 1.8; color: #444; margin-bottom: 4px; }
  .content strong { font-weight: 500; color: #1a1a1a; }
  .footer { text-align: center; font-size: 11px; color: #bbb; margin-top: 2rem; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <div>
      <h1>Vibe Audit</h1>
      <div class="meta">Generated ${new Date().toLocaleString()}</div>
    </div>
    <div class="badge">vibe-cli</div>
  </div>
  <div class="card">
    <div class="card-label">Full analysis</div>
    <div class="content">${renderedContent}</div>
  </div>
  <div class="footer">generated by vibe-cli</div>
</div>
</body>
</html>`;
}

program
    .command("audit")
    .description("Analyze your codebase")
    .action(async () => {
        console.log("\nScanning project...\n");

        const files = getFiles(process.cwd());
        const importantFiles = files
            .filter((f) => f.endsWith(".js") || f.endsWith(".ts") || f.includes("api") || f.includes("service"))
            .slice(0, 15);

        const content = importantFiles.map((file) => ({
            file,
            code: fs.readFileSync(file, "utf-8").slice(0, 1500),
        }));

        const prompt = `You are a senior software architect analyzing a founder's codebase.
Analyze this codebase and provide:
1. System overview
2. Core flows
3. Risks
4. Structure scores (out of 10)
5. Moat vs commodity
6. What to fix next

Be concise, specific, and opinionated. Do not give generic advice.

Files:
${JSON.stringify(content, null, 2)}`;

        const res = await client.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [{ role: "user", content: prompt }],
        });

        const output = res.choices[0].message.content;
        console.log(output);

        const html = generateHTML(output);
        const reportPath = path.join(process.cwd(), "vibe-report.html");
        fs.writeFileSync(reportPath, html);
        console.log(`\nReport saved: ${reportPath}`);

        try {
            execSync(`open "${reportPath}"`);
        } catch (e) {
            console.log("Open manually: " + reportPath);
        }
    });

program.parse();